# Generated by Django 5.0 on 2023-12-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', '-created_at'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'price', '-created_at', 'category')},
        ),
    ]
